repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: '23.3.0'
    hooks:
    -   id: black
        args: ["--line-length=88"]
-   repo: https://github.com/pycqa/isort
    rev: '5.12.0'
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length=88"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.2.0'
    hooks:
    -   id: mypy
        exclude: 'docs/'
        additional_dependencies: [types-requests, types-PyYAML]
-   repo: https://github.com/PyCQA/flake8
    rev: '6.0.0'
    hooks:
      - id: flake8
-   repo: https://github.com/python-poetry/poetry
    rev: '1.4.2'
    hooks:
      - id: poetry-lock
      - id: poetry-export
        args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]
